[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/generateDesign"
  to = "/.netlify/functions/generateDesign"
  status = 200

[[redirects]]
  from = "/api/analyzeImage"
  to = "/.netlify/functions/analyzeImage"
  status = 200

[[redirects]]
  from = "/api/generateImage"
  to = "/.netlify/functions/generateImage"
  status = 200